/** @type {import('tailwindcss').config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          900: '#0c4a6e',
        },
        accent: {
          500: '#f59e0b',
          600: '#d97706',
        },
        "primary-fixed-dim": "#bec6e0",
        "surface-container": "#eceef0",
        "inverse-surface": "#2d3133",
        "surface-container-high": "#e6e8ea",
        "on-tertiary-fixed-variant": "#004395",
        "on-primary-container": "#7c839b",
        "secondary-container": "#d5e3fd",
        "on-primary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d8e2ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#001a42",
        "surface-container-low": "#f2f4f6",
        "secondary-fixed": "#d5e3fd",
        "primary-fixed": "#dae2fd",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#0d1c2f",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#bec6e0",
        "on-surface": "#191c1e",
        "surface": "#f7f9fb",
        "surface-tint": "#565e74",
        "primary-container": "#131b2e",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary-container": "#001a42",
        "on-tertiary-container": "#3980f4",
        "on-background": "#191c1e",
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "primary": "#000000",
        "inverse-on-surface": "#eff1f3",
        "secondary": "#515f74",
        "background": "#f7f9fb",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#adc6ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#45464d",
        "outline": "#76777d",
        "on-secondary-container": "#57657b",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#b9c7e0",
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        displayLg: ['Inter', 'sans-serif'],
        labelSm: ['Inter', 'sans-serif'],
        headlineSm: ['Inter', 'sans-serif'],
        labelMd: ['Inter', 'sans-serif'],
        bodyLg: ['Inter', 'sans-serif'],
        bodyMd: ['Inter', 'sans-serif'],
        headlineMd: ['Inter', 'sans-serif'],
      },
      fontSize: {
        displayLgMobile: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: 700 }],
        displayLg: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: 700 }],
        labelSm: ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: 600 }],
        headlineSm: ['24px', { lineHeight: '32px', fontWeight: 600 }],
        labelMd: ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: 500 }],
        bodyLg: ['18px', { lineHeight: '28px', fontWeight: 400 }],
        bodyMd: ['16px', { lineHeight: '24px', fontWeight: 400 }],
        headlineMd: ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: 600 }],
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'max-width': '1280px',
        'gutter': '24px',
        'xl': '40px',
        'lg': '24px',
        'md': '16px',
        'sm': '8px',
        'base': '4px',
        'xs': '4px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
