import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { vehicles } from '../src/data/vehicles.js';
import Vehicle from './models/Vehicle.js';
import User from './models/User.js';
import VehicleAttribute from './models/VehicleAttribute.js';
import City from './models/City.js';
import Province from './models/Province.js';
import Make from './models/Make.js';
import VehicleModel from './models/VehicleModel.js';

dotenv.config();

const ATTRIBUTE_SEED = [
  { category: 'provinces', value: 'Sindh', label: 'Sindh', order: 1 },
  { category: 'provinces', value: 'Punjab', label: 'Punjab', order: 2 },
  { category: 'provinces', value: 'KPK', label: 'KPK', order: 3 },
  { category: 'makes', value: 'Toyota', label: 'Toyota', order: 1 },
  { category: 'makes', value: 'Honda', label: 'Honda', order: 2 },
  { category: 'makes', value: 'Suzuki', label: 'Suzuki', order: 3 },
  { category: 'priceRanges', value: 'Under 500K', label: 'Under 500K', order: 1 },
  { category: 'priceRanges', value: '500K - 1M', label: '500K - 1M', order: 2 },
  { category: 'priceRanges', value: '1M - 2M', label: '1M - 2M', order: 3 },
  { category: 'years', value: '2024', label: '2024', order: 1 },
  { category: 'years', value: '2023', label: '2023', order: 2 },
  { category: 'years', value: '2022', label: '2022', order: 3 },
  { category: 'mileages', value: '0-10K', label: '0-10K Km', order: 1 },
  { category: 'mileages', value: '10K-30K', label: '10K-30K Km', order: 2 },
  { category: 'mileages', value: '30K+', label: '30K+ Km', order: 3 },
  { category: 'registeredIn', value: 'Pakistan', label: 'Pakistan', order: 1 },
  { category: 'transmissions', value: 'Automatic', label: 'Automatic', order: 1 },
  { category: 'transmissions', value: 'Manual', label: 'Manual', order: 2 },
  { category: 'transmissions', value: 'CVT', label: 'CVT', order: 3 },
  { category: 'colors', value: 'White', label: 'White', order: 1 },
  { category: 'colors', value: 'Black', label: 'Black', order: 2 },
  { category: 'colors', value: 'Silver', label: 'Silver', order: 3 },
  { category: 'engineTypes', value: 'Petrol', label: 'Petrol', order: 1 },
  { category: 'engineTypes', value: 'Diesel', label: 'Diesel', order: 2 },
  { category: 'engineTypes', value: 'Hybrid', label: 'Hybrid', order: 3 },
  { category: 'engineCapacities', value: '1300cc', label: '1300cc', order: 1 },
  { category: 'engineCapacities', value: '1500cc', label: '1500cc', order: 2 },
  { category: 'engineCapacities', value: '2000cc', label: '2000cc', order: 3 },
  { category: 'assembly', value: 'Local', label: 'Local', order: 1 },
  { category: 'assembly', value: 'Imported', label: 'Imported', order: 2 },
  { category: 'bodyTypes', value: 'Sedan', label: 'Sedan', order: 1 },
  { category: 'bodyTypes', value: 'SUV', label: 'SUV', order: 2 },
  { category: 'bodyTypes', value: 'Hatchback', label: 'Hatchback', order: 3 },
  { category: 'doors', value: '4', label: '4 Doors', order: 1 },
  { category: 'doors', value: '5', label: '5 Doors', order: 2 },
  { category: 'seatingCapacity', value: '5', label: '5 Seats', order: 1 },
  { category: 'seatingCapacity', value: '7', label: '7 Seats', order: 2 },
  { category: 'modelCategory', value: 'New', label: 'New', order: 1 },
  { category: 'modelCategory', value: 'Used', label: 'Used', order: 2 },
  { category: 'trustedCars', value: 'Yes', label: 'Yes', order: 1 },
  { category: 'trustedCars', value: 'No', label: 'No', order: 2 },
];

export const PROVINCE_SEED = [
  { provinceId: 'PB', provinceName: 'Punjab' },
  { provinceId: 'SD', provinceName: 'Sindh' },
  { provinceId: 'KP', provinceName: 'KPK' },
  { provinceId: 'BA', provinceName: 'Balochistan' },
  { provinceId: 'ICT', provinceName: 'Islamabad Capital Territory' },
  { provinceId: 'AJK', provinceName: 'Azad Jammu and Kashmir' },
  { provinceId: 'GB', provinceName: 'Gilgit-Baltistan' },
  { provinceId: 'FATA', provinceName: 'Federally Administered Tribal Areas' },
];

export const preparedProvinces = PROVINCE_SEED.map((p) => ({
  provinceId: p.provinceId,
  provinceName: p.provinceName,
  active: true,
}));

export const MAKE_SEED = [
  { makeId: 'TOY', makeName: 'Toyota' },
  { makeId: 'SUZ', makeName: 'Suzuki' },
  { makeId: 'HON', makeName: 'Honda' },
  { makeId: 'DAI', makeName: 'Daihatsu' },
  { makeId: 'ADM', makeName: 'Adam' },
  { makeId: 'AON', makeName: 'Aion' },
  { makeId: 'ALE', makeName: 'Alektra' },
  { makeId: 'AUD', makeName: 'Audi' },
  { makeId: 'AUS', makeName: 'Austin' },
  { makeId: 'BAI', makeName: 'BAIC' },
  { makeId: 'BMW', makeName: 'BMW' },
  { makeId: 'BYD', makeName: 'BYD' },
  { makeId: 'CAD', makeName: 'Cadillac' },
  { makeId: 'CHA', makeName: 'Changan' },
  { makeId: 'CHE', makeName: 'Chery' },
  { makeId: 'CHV', makeName: 'Chevrolet' },
  { makeId: 'CHR', makeName: 'Chrysler' },
  { makeId: 'CLA', makeName: 'Classic Cars' },
  { makeId: 'DFS', makeName: 'DFSK' },
  { makeId: 'DAE', makeName: 'Daehan' },
  { makeId: 'DAW', makeName: 'Daewoo' },
  { makeId: 'DAT', makeName: 'Datsun' },
  { makeId: 'DEE', makeName: 'Deepal' },
  { makeId: 'DOD', makeName: 'Dodge' },
  { makeId: 'DON', makeName: 'Dongfeng' },
  { makeId: 'FAW', makeName: 'FAW' },
  { makeId: 'FIA', makeName: 'Fiat' },
  { makeId: 'FER', makeName: 'Ferrari' },
  { makeId: 'FOR', makeName: 'Ford' },
  { makeId: 'FTH', makeName: 'Forthing' },
  { makeId: 'FOT', makeName: 'Foton' },
  { makeId: 'GAC', makeName: 'GAC' },
  { makeId: 'GMC', makeName: 'GMC' },
  { makeId: 'GUG', makeName: 'GUGO' },
  { makeId: 'GWM', makeName: 'GWM' },
  { makeId: 'GEN', makeName: 'Genesis' },
  { makeId: 'HAV', makeName: 'Haval' },
  { makeId: 'HIN', makeName: 'Hino' },
  { makeId: 'HNR', makeName: 'Honri' },
  { makeId: 'HUM', makeName: 'Hummer' },
  { makeId: 'HYP', makeName: 'Hyptec' },
  { makeId: 'HYU', makeName: 'Hyundai' },
  { makeId: 'INV', makeName: 'Inverex' },
  { makeId: 'ISU', makeName: 'Isuzu' },
  { makeId: 'JAC', makeName: 'JAC' },
  { makeId: 'JMC', makeName: 'JMC' },
  { makeId: 'JME', makeName: 'JMEV' },
  { makeId: 'JWF', makeName: 'JW Forland' },
  { makeId: 'JAE', makeName: 'Jaecoo' },
  { makeId: 'JAG', makeName: 'Jaguar' },
  { makeId: 'JEE', makeName: 'Jeep' },
  { makeId: 'JET', makeName: 'Jetour' },
  { makeId: 'KIA', makeName: 'KIA' },
  { makeId: 'LAR', makeName: 'Land Rover' },
  { makeId: 'LEX', makeName: 'Lexus' },
  { makeId: 'MG', makeName: 'MG' },
  { makeId: 'MIN', makeName: 'MINI' },
  { makeId: 'MAS', makeName: 'Master' },
  { makeId: 'MAZ', makeName: 'Mazda' },
  { makeId: 'MCL', makeName: 'McLaren' },
  { makeId: 'MBZ', makeName: 'Mercedes Benz' },
  { makeId: 'MIT', makeName: 'Mitsubishi' },
  { makeId: 'NIS', makeName: 'Nissan' },
  { makeId: 'ORA', makeName: 'ORA' },
  { makeId: 'OMO', makeName: 'Omoda' },
  { makeId: 'OPE', makeName: 'Opel' },
  { makeId: 'PEO', makeName: 'Peugeot' },
  { makeId: 'POR', makeName: 'Porsche' },
  { makeId: 'PRI', makeName: 'Prince' },
  { makeId: 'PRO', makeName: 'Proton' },
  { makeId: 'RAR', makeName: 'Range Rover' },
  { makeId: 'RID', makeName: 'Riddara' },
  { makeId: 'RIN', makeName: 'Rinco' },
  { makeId: 'ROL', makeName: 'Rolls Royce' },
  { makeId: 'SER', makeName: 'Seres' },
  { makeId: 'SMA', makeName: 'Smart' },
  { makeId: 'SOG', makeName: 'Sogo' },
  { makeId: 'SSA', makeName: 'SsangYong' },
  { makeId: 'SUB', makeName: 'Subaru' },
  { makeId: 'TAN', makeName: 'Tank' },
  { makeId: 'TES', makeName: 'Tesla' },
  { makeId: 'UNI', makeName: 'United' },
  { makeId: 'VAU', makeName: 'Vauxhall' },
  { makeId: 'VW', makeName: 'Volkswagen' },
  { makeId: 'VOL', makeName: 'Volvo' },
  { makeId: 'WIL', makeName: 'Willys' },
  { makeId: 'ZOT', makeName: 'ZOTYE' },
  { makeId: 'ZEE', makeName: 'Zeekr' },
];

export const preparedMakes = MAKE_SEED.map((m) => ({
  makeId: m.makeId,
  makeName: m.makeName,
  active: true,
}));

export const MODEL_SEED = [
  { modelId: 'COROLLA', modelName: 'Corolla', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'YARIS_SEDAN', modelName: 'Yaris Sedan', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'FORTUNER', modelName: 'Fortuner', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'AQUA', modelName: 'Aqua', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PRIUS', modelName: 'Prius', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: '4_RUNNER', modelName: '4 Runner', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: '86', modelName: '86', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ALLION', modelName: 'Allion', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ALPHARD', modelName: 'Alphard', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ALPHARD_V', modelName: 'Alphard V', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'AURIS', modelName: 'Auris', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'AVANZA', modelName: 'Avanza', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'AVENSIS', modelName: 'Avensis', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'AYGO', modelName: 'Aygo', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'BB', modelName: 'B B', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'BELTA', modelName: 'Belta', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CHR', modelName: 'C-HR', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CALDINA', modelName: 'Caldina', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CAMI', modelName: 'Cami', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CAMRY', modelName: 'Camry', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CARINA', modelName: 'Carina', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CELICA', modelName: 'Celica', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CELSIOR', modelName: 'Celsior', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COASTER', modelName: 'Coaster', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_AXIO', modelName: 'Corolla Axio', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_CROSS', modelName: 'Corolla Cross', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_FIELDER', modelName: 'Corolla Fielder', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_HATCHBACK', modelName: 'Corolla Hatchback', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_SPACIO', modelName: 'Corolla Spacio', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_TOURING', modelName: 'Corolla Touring', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'COROLLA_VERSO', modelName: 'Corolla Verso', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CORONA', modelName: 'Corona', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CRESSIDA', modelName: 'Cressida', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CRESTA', modelName: 'Cresta', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'CROWN', modelName: 'Crown', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'DUET', modelName: 'Duet', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'DYNA', modelName: 'Dyna', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ESQUIRE', modelName: 'Esquire', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ESTIMA', modelName: 'Estima', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'FJ_CRUISER', modelName: 'FJ Cruiser', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'HARRIER', modelName: 'Harrier', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'HIACE', modelName: 'Hiace', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'HILUX', modelName: 'Hilux', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'IQ', modelName: 'iQ', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ISIS', modelName: 'ISIS', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'IST', modelName: 'IST', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'LAND_CRUISER', modelName: 'Land Cruiser', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'LITEACE', modelName: 'LiteAce', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'LUCIDA', modelName: 'Lucida', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'MR2', modelName: 'MR2', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'MARK_2', modelName: 'Mark II', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'MARK_X', modelName: 'Mark X', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'NOAH', modelName: 'Noah', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PASSO', modelName: 'Passo', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PIXIS_EPOCH', modelName: 'Pixis Epoch', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PIXIS_JOY', modelName: 'Pixis Joy', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PIXIS_MEGA', modelName: 'Pixis Mega', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PIXIS_SPACE', modelName: 'Pixis Space', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PIXIS_VAN', modelName: 'Pixis Van', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PLATZ', modelName: 'Platz', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PORTE', modelName: 'Porte', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PRADO', modelName: 'Prado', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PREMIO', modelName: 'Premio', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PRIUS_ALPHA', modelName: 'Prius Alpha', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'PROBOX', modelName: 'Probox', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RACTIS', modelName: 'Ractis', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RAIZE', modelName: 'Raize', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RAUM', modelName: 'Raum', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RAV4', modelName: 'RAV4', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'ROOMY', modelName: 'Roomy', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RUMION', modelName: 'Rumion', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'RUSH', modelName: 'Rush', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'SERA', modelName: 'Sera', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'SIENTA', modelName: 'Sienta', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'STARLET', modelName: 'Starlet', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'SUCCEED', modelName: 'Succeed', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'SURF', modelName: 'Surf', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'TACOMA', modelName: 'Tacoma', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'TANK', modelName: 'Tank', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'TOWN_ACE', modelName: 'Town Ace', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'TUNDRA', modelName: 'Tundra', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'VAN', modelName: 'Van', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'VEROSSA', modelName: 'Verossa', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'VITZ', modelName: 'Vitz', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'VOXY', modelName: 'Voxy', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'WISH', modelName: 'Wish', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'YARIS_CROSS', modelName: 'Yaris Cross', brandId: 'TOY', brandName: 'Toyota' },
  { modelId: 'YARIS_HATCHBACK', modelName: 'Yaris Hatchback', brandId: 'TOY', brandName: 'Toyota' },

  // Honda
  { modelId: 'CITY', modelName: 'City', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'CIVIC', modelName: 'Civic', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'VEZEL', modelName: 'Vezel', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'N_WGN', modelName: 'N Wgn', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'ACCORD', modelName: 'Accord', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'ACTY', modelName: 'Acty', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'AIRWAVE', modelName: 'Airwave', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'BRV', modelName: 'BR-V', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'BEAT', modelName: 'Beat', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'CRV', modelName: 'CR-V', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'CRZ', modelName: 'CR-Z', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'CR_X', modelName: 'Cr X', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'CROSS_ROAD', modelName: 'Cross Road', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'FIT', modelName: 'Fit', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'FIT_ARIA', modelName: 'Fit Aria', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'FREED', modelName: 'Freed', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'GRACE_HYBRID', modelName: 'Grace Hybrid', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'HRV', modelName: 'HR-V', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'INSIGHT', modelName: 'Insight', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'INTEGRA', modelName: 'Integra', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'JADE', modelName: 'Jade', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'LIFE', modelName: 'Life', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'N_BOX', modelName: 'N Box', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'N_ONE', modelName: 'N One', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'N_VAN', modelName: 'N-Van', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'ODYSSEY', modelName: 'Odyssey', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'S660', modelName: 'S660', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'SPIKE', modelName: 'Spike', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'STREAM', modelName: 'Stream', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'THATS', modelName: 'Thats', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'TORNEO', modelName: 'Torneo', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'VAMOS', modelName: 'Vamos', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'VAMOS_HOBIO', modelName: 'Vamos Hobio', brandId: 'HON', brandName: 'Honda' },
  { modelId: 'ZEST', modelName: 'Zest', brandId: 'HON', brandName: 'Honda' },

  // Jaguar
  { modelId: 'F-PACE', modelName: 'F-Pace', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'F-TYPE', modelName: 'F-Type', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'I-PACE', modelName: 'I-Pace', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'XE', modelName: 'XE', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'XF', modelName: 'XF', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'XJ', modelName: 'XJ', brandId: 'JAG', brandName: 'Jaguar' },
  { modelId: 'E-PACE', modelName: 'E-Pace', brandId: 'JAG', brandName: 'Jaguar' },

  // Suzuki
  { modelId: 'CULTUS', modelName: 'Cultus', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'ALTO', modelName: 'Alto', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'WAGONR', modelName: 'Wagon R', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SWIFT', modelName: 'Swift', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'APV', modelName: 'APV', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'AERIO', modelName: 'Aerio', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'ALTO_LAPIN', modelName: 'Alto Lapin', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'BALENO', modelName: 'Baleno', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'BOLAN', modelName: 'Bolan', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'CAPPUCCINO', modelName: 'Cappuccino', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'CARRY', modelName: 'Carry', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'CELERIO', modelName: 'Celerio', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'CERVO', modelName: 'Cervo', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'CIAZ', modelName: 'Ciaz', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'EVERY', modelName: 'Every', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'EVERY_WAGON', modelName: 'Every Wagon', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'FX', modelName: 'FX', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'FRONX', modelName: 'Fronx', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'HUSTLER', modelName: 'Hustler', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'JIMNY', modelName: 'Jimny', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'KEI', modelName: 'Kei', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'KHYBER', modelName: 'Khyber', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'KIZASHI', modelName: 'Kizashi', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'LIANA', modelName: 'Liana', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'LJ80', modelName: 'Lj80', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'MR_WAGON', modelName: 'MR Wagon', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'MARGALLA', modelName: 'Margalla', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'MEGA_CARRY_XTRA', modelName: 'Mega Carry Xtra', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'MEHRAN', modelName: 'Mehran', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'PALETTE', modelName: 'Palette', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'POTOHAR', modelName: 'Potohar', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'RAVI', modelName: 'Ravi', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'S_CROSS', modelName: 'S-Cross', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SAMURAI', modelName: 'Samurai', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SIERRA', modelName: 'Sierra', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SJ410', modelName: 'Sj410', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SOLIO', modelName: 'Solio', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SPACIA', modelName: 'Spacia', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SPLASH', modelName: 'Splash', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SX4', modelName: 'Sx4', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'TWIN', modelName: 'Twin', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'VITARA', modelName: 'Vitara', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'XBEE', modelName: 'Xbee', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'ERTIGA', modelName: 'Ertiga', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'XL7', modelName: 'XL7', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'SPRESSO', modelName: 'S-Presso', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'IGNIS', modelName: 'Ignis', brandId: 'SUZ', brandName: 'Suzuki' },
  { modelId: 'KARIMUN', modelName: 'Karimun', brandId: 'SUZ', brandName: 'Suzuki' },

  // Ferrari
  { modelId: '296', modelName: '296', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '308', modelName: '308', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '456', modelName: '456', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '488', modelName: '488', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '575', modelName: '575', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '612', modelName: '612', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '812', modelName: '812', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '12CILINDRI', modelName: '12Cilindri', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '348_TS', modelName: '348 TS', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '360_CHALLENGE', modelName: '360 Challenge', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '458_ITALIA', modelName: '458 Italia', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '458_SPECIALE', modelName: '458 Speciale', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '488_GTB', modelName: '488 GTB', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '488_PISTA', modelName: '488 Pista', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '488_SPIDER', modelName: '488 Spider', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '512_TR', modelName: '512 TR', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '550_BARCHETTA', modelName: '550 Barchetta', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '599_GTB', modelName: '599 GTB', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: '849_TESTAROSSA', modelName: '849 Testarossa', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'AMALFI', modelName: 'Amalfi', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'CALIFORNIA', modelName: 'California', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'F12', modelName: 'F12', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'F355', modelName: 'F355', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'F430', modelName: 'F430', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'F8_SPIDER', modelName: 'F8 Spider', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'F8_TRIBUTO', modelName: 'F8 Tributo', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'GTC4', modelName: 'GTC4', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'PORTOFINO', modelName: 'Portofino', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'PORTOFINO_M', modelName: 'Portofino M', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'PUROSANGUE', modelName: 'Purosangue', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'ROMA', modelName: 'Roma', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'SF90', modelName: 'SF90', brandId: 'FER', brandName: 'Ferrari' },
  { modelId: 'TESTAROSSA', modelName: 'Testarossa', brandId: 'FER', brandName: 'Ferrari' },

  // BMW
  { modelId: '3_SERIES', modelName: '3 Series', brandId: 'BMW', brandName: 'BMW' },
  { modelId: '5_SERIES', modelName: '5 Series', brandId: 'BMW', brandName: 'BMW' },
  { modelId: '7_SERIES', modelName: '7 Series', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'X1', modelName: 'X1', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'X3', modelName: 'X3', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'X5', modelName: 'X5', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'X7', modelName: 'X7', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'M3', modelName: 'M3', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'M5', modelName: 'M5', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'I4', modelName: 'i4', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'IX', modelName: 'iX', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'IX3', modelName: 'iX3', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'Z4', modelName: 'Z4', brandId: 'BMW', brandName: 'BMW' },
  { modelId: '6_SERIES', modelName: '6 Series', brandId: 'BMW', brandName: 'BMW' },
  { modelId: '8_SERIES', modelName: '8 Series', brandId: 'BMW', brandName: 'BMW' },
  { modelId: 'X6', modelName: 'X6', brandId: 'BMW', brandName: 'BMW' },

  // Mercedes Benz
  { modelId: 'A_CLASS', modelName: 'A-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'C_CLASS', modelName: 'C-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'E_CLASS', modelName: 'E-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'S_CLASS', modelName: 'S-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'G_CLASS', modelName: 'G-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'GLA', modelName: 'GLA', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'GLC', modelName: 'GLC', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'GLE', modelName: 'GLE', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'GLS', modelName: 'GLS', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'AMG_GT', modelName: 'AMG GT', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'EQS', modelName: 'EQS', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'EQB', modelName: 'EQB', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'B_CLASS', modelName: 'B-Class', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'CLA', modelName: 'CLA', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'CLS', modelName: 'CLS', brandId: 'MBZ', brandName: 'Mercedes Benz' },
  { modelId: 'SL', modelName: 'SL', brandId: 'MBZ', brandName: 'Mercedes Benz' },

  // Hyundai
  { modelId: 'ELANTRA', modelName: 'Elantra', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'SONATA', modelName: 'Sonata', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'TUCSON', modelName: 'Tucson', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'SANTA_FE', modelName: 'Santa Fe', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'CRETA', modelName: 'Creta', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'IONIQ5', modelName: 'Ioniq 5', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'IONIQ6', modelName: 'Ioniq 6', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'KONA', modelName: 'Kona', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'VENUE', modelName: 'Venue', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'ACCENT', modelName: 'Accent', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'PALISADE', modelName: 'Palisade', brandId: 'HYU', brandName: 'Hyundai' },
  { modelId: 'STARIA', modelName: 'Staria', brandId: 'HYU', brandName: 'Hyundai' },

  // KIA
  { modelId: 'SPORTAGE', modelName: 'Sportage', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'SORENTO', modelName: 'Sorento', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'TELLURIDE', modelName: 'Telluride', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'SELTOS', modelName: 'Seltos', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'SONET', modelName: 'Sonet', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'FORTE', modelName: 'Forte', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'K5', modelName: 'K5', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'K8', modelName: 'K8', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'STINGER', modelName: 'Stinger', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'CARNIVAL', modelName: 'Carnival', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'PICANTO', modelName: 'Picanto', brandId: 'KIA', brandName: 'KIA' },
  { modelId: 'RIO', modelName: 'Rio', brandId: 'KIA', brandName: 'KIA' },

  // Audi
  { modelId: 'A4', modelName: 'A4', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'A6', modelName: 'A6', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'A8', modelName: 'A8', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'Q3', modelName: 'Q3', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'Q5', modelName: 'Q5', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'Q7', modelName: 'Q7', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'Q8', modelName: 'Q8', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'RS6', modelName: 'RS6', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'RS7', modelName: 'RS7', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'E_TRON', modelName: 'e-tron', brandId: 'AUD', brandName: 'Audi' },
  { modelId: 'Q5_SPORTBACK', modelName: 'Q5 Sportback', brandId: 'AUD', brandName: 'Audi' },

  // Porsche
  { modelId: '911', modelName: '911', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'CAYENNE', modelName: 'Cayenne', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'MACAN', modelName: 'Macan', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'PANAMERA', modelName: 'Panamera', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'TAYCAN', modelName: 'Taycan', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'BOXSTER', modelName: 'Boxster', brandId: 'POR', brandName: 'Porsche' },
  { modelId: 'CAYMAN', modelName: 'Cayman', brandId: 'POR', brandName: 'Porsche' },

  // Land Rover
  { modelId: 'DEFENDER', modelName: 'Defender', brandId: 'LAR', brandName: 'Land Rover' },
  { modelId: 'DISCOVERY', modelName: 'Discovery', brandId: 'LAR', brandName: 'Land Rover' },
  { modelId: 'RANGE_ROVER', modelName: 'Range Rover', brandId: 'LAR', brandName: 'Land Rover' },
  { modelId: 'RANGE_ROVER_SPORT', modelName: 'Range Rover Sport', brandId: 'LAR', brandName: 'Land Rover' },
  { modelId: 'RANGE_ROVER_VELAR', modelName: 'Range Rover Velar', brandId: 'LAR', brandName: 'Land Rover' },
  { modelId: 'RANGE_ROVER_EVOQUE', modelName: 'Range Rover Evoque', brandId: 'LAR', brandName: 'Land Rover' },

  // Range Rover
  { modelId: 'RR', modelName: 'Range Rover', brandId: 'RAR', brandName: 'Range Rover' },
  { modelId: 'RR_SPORT', modelName: 'Range Rover Sport', brandId: 'RAR', brandName: 'Range Rover' },
  { modelId: 'RR_VELAR', modelName: 'Range Rover Velar', brandId: 'RAR', brandName: 'Range Rover' },
  { modelId: 'RR_EVOQUE', modelName: 'Range Rover Evoque', brandId: 'RAR', brandName: 'Range Rover' },

  // Tesla
  { modelId: 'MODEL_S', modelName: 'Model S', brandId: 'TES', brandName: 'Tesla' },
  { modelId: 'MODEL_3', modelName: 'Model 3', brandId: 'TES', brandName: 'Tesla' },
  { modelId: 'MODEL_X', modelName: 'Model X', brandId: 'TES', brandName: 'Tesla' },
  { modelId: 'MODEL_Y', modelName: 'Model Y', brandId: 'TES', brandName: 'Tesla' },
  { modelId: 'CYBERTRUCK', modelName: 'Cybertruck', brandId: 'TES', brandName: 'Tesla' },

  // Mitsubishi
  { modelId: 'MIRAGE', modelName: 'Mirage', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'OUTLANDER', modelName: 'Outlander', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'PAJERO', modelName: 'Pajero', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'LANCER', modelName: 'Lancer', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'ECLIPSE_CROSS', modelName: 'Eclipse Cross', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'XPANDER', modelName: 'Xpander', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'PAJERO_SPORT', modelName: 'Pajero Sport', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'ASX', modelName: 'ASX', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'DELICA', modelName: 'Delica', brandId: 'MIT', brandName: 'Mitsubishi' },
  { modelId: 'FUSO', modelName: 'Fuso', brandId: 'MIT', brandName: 'Mitsubishi' },

  // Daihatsu
  { modelId: 'BOON', modelName: 'Boon', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'TERIOS', modelName: 'Terios', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'MIRA', modelName: 'Mira', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'SIRION', modelName: 'Sirion', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'XENIA', modelName: 'Xenia', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'GRAN_MOVE', modelName: 'Gran Move', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'ROCKY', modelName: 'Rocky', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'ATRAI', modelName: 'Atrai', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'HIJET', modelName: 'Hijet', brandId: 'DAI', brandName: 'Daihatsu' },
  { modelId: 'CHARADE', modelName: 'Charade', brandId: 'DAI', brandName: 'Daihatsu' },

  // MG
  { modelId: 'MG3', modelName: 'MG3', brandId: 'MG', brandName: 'MG' },
  { modelId: 'MG5', modelName: 'MG5', brandId: 'MG', brandName: 'MG' },
  { modelId: 'MG6', modelName: 'MG6', brandId: 'MG', brandName: 'MG' },
  { modelId: 'HS', modelName: 'HS', brandId: 'MG', brandName: 'MG' },
  { modelId: 'ZS', modelName: 'ZS', brandId: 'MG', brandName: 'MG' },
  { modelId: 'RX8', modelName: 'RX8', brandId: 'MG', brandName: 'MG' },
  { modelId: 'MARVEL_R', modelName: 'Marvel R', brandId: 'MG', brandName: 'MG' },

  // Changan
  { modelId: 'CS35', modelName: 'CS35', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'CS55', modelName: 'CS55', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'CS75', modelName: 'CS75', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'EADO', modelName: 'Eado', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'UNI_T', modelName: 'UNI-T', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'UNI_K', modelName: 'UNI-K', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'BENBEN', modelName: 'Benben', brandId: 'CHA', brandName: 'Changan' },
  { modelId: 'ALSVIN', modelName: 'Alsvin', brandId: 'CHA', brandName: 'Changan' },

  // BYD
  { modelId: 'QIN', modelName: 'Qin', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'TANG', modelName: 'Tang', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'SONG', modelName: 'Song', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'YUAN', modelName: 'Yuan', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'HAN', modelName: 'Han', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'SEAL', modelName: 'Seal', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'DOLPHIN', modelName: 'Dolphin', brandId: 'BYD', brandName: 'BYD' },
  { modelId: 'ATTO3', modelName: 'Atto 3', brandId: 'BYD', brandName: 'BYD' },

  // Haval
  { modelId: 'H6', modelName: 'H6', brandId: 'HAV', brandName: 'Haval' },
  { modelId: 'H9', modelName: 'H9', brandId: 'HAV', brandName: 'Haval' },
  { modelId: 'JOLION', modelName: 'Jolion', brandId: 'HAV', brandName: 'Haval' },
  { modelId: 'DARGO', modelName: 'Dargo', brandId: 'HAV', brandName: 'Haval' },
  { modelId: 'F7', modelName: 'F7', brandId: 'HAV', brandName: 'Haval' },
  { modelId: 'F7X', modelName: 'F7x', brandId: 'HAV', brandName: 'Haval' },

  // Chery
  { modelId: 'QQ', modelName: 'QQ', brandId: 'CHE', brandName: 'Chery' },
  { modelId: 'ARRIZO', modelName: 'Arrizo', brandId: 'CHE', brandName: 'Chery' },
  { modelId: 'TIGGO', modelName: 'Tiggo', brandId: 'CHE', brandName: 'Chery' },
  { modelId: 'TIGGO8', modelName: 'Tiggo 8', brandId: 'CHE', brandName: 'Chery' },
  { modelId: 'OMODA5', modelName: 'Omoda 5', brandId: 'CHE', brandName: 'Chery' },
  { modelId: 'E5', modelName: 'E5', brandId: 'CHE', brandName: 'Chery' },

  // DFSK
  { modelId: 'GLORY_500', modelName: 'Glory 500', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'GLORY_580', modelName: 'Glory 580', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'GLORY_560', modelName: 'Glory 560', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'C31', modelName: 'C31', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'C32', modelName: 'C32', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'K01', modelName: 'K01', brandId: 'DFS', brandName: 'DFSK' },
  { modelId: 'K02', modelName: 'K02', brandId: 'DFS', brandName: 'DFSK' },

  // Prince
  { modelId: 'PEARL', modelName: 'Pearl', brandId: 'PRI', brandName: 'Prince' },
  { modelId: 'GLORY', modelName: 'Glory', brandId: 'PRI', brandName: 'Prince' },
  { modelId: 'SPEED', modelName: 'Speed', brandId: 'PRI', brandName: 'Prince' },
  { modelId: 'ROYAL', modelName: 'Royal', brandId: 'PRI', brandName: 'Prince' },
  { modelId: 'CROWN_PRINCE', modelName: 'Crown', brandId: 'PRI', brandName: 'Prince' },

  // Proton
  { modelId: 'PERSONA', modelName: 'Persona', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'SAGA', modelName: 'Saga', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'X70', modelName: 'X70', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'X50', modelName: 'X50', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'X80', modelName: 'X80', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'EXORA', modelName: 'Exora', brandId: 'PRO', brandName: 'Proton' },
  { modelId: 'PREVE', modelName: 'Preve', brandId: 'PRO', brandName: 'Proton' },

  // FAW
  { modelId: 'BESTURN', modelName: 'Besturn', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'BESTUNE', modelName: 'Bestune', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'FAW_X80', modelName: 'X80', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'T77', modelName: 'T77', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'T99', modelName: 'T99', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'J6', modelName: 'J6', brandId: 'FAW', brandName: 'FAW' },
  { modelId: 'J7', modelName: 'J7', brandId: 'FAW', brandName: 'FAW' },

  // Dongfeng
  { modelId: 'AX7', modelName: 'AX7', brandId: 'DON', brandName: 'Dongfeng' },
  { modelId: 'A9', modelName: 'A9', brandId: 'DON', brandName: 'Dongfeng' },
  { modelId: 'S50', modelName: 'S50', brandId: 'DON', brandName: 'Dongfeng' },
  { modelId: 'H30', modelName: 'H30', brandId: 'DON', brandName: 'Dongfeng' },

  // GWM
  { modelId: 'HAVAL_H6', modelName: 'Haval H6', brandId: 'GWM', brandName: 'GWM' },
  { modelId: 'TANK300', modelName: 'Tank 300', brandId: 'GWM', brandName: 'GWM' },
  { modelId: 'TANK500', modelName: 'Tank 500', brandId: 'GWM', brandName: 'GWM' },
  { modelId: 'WEY_VV7', modelName: 'WEY VV7', brandId: 'GWM', brandName: 'GWM' },
  { modelId: 'ORA_GOOD_CAT', modelName: 'ORA Good Cat', brandId: 'GWM', brandName: 'GWM' },
  { modelId: 'POER', modelName: 'Poer', brandId: 'GWM', brandName: 'GWM' },

  // JAECOO
  { modelId: 'J7_JAECOO', modelName: 'J7', brandId: 'JAE', brandName: 'Jaecoo' },
  { modelId: 'J8', modelName: 'J8', brandId: 'JAE', brandName: 'Jaecoo' },

  // McLaren
  { modelId: '720S', modelName: '720S', brandId: 'MCL', brandName: 'McLaren' },
  { modelId: '765LT', modelName: '765LT', brandId: 'MCL', brandName: 'McLaren' },
  { modelId: '750S', modelName: '750S', brandId: 'MCL', brandName: 'McLaren' },
  { modelId: 'ARTURA', modelName: 'Artura', brandId: 'MCL', brandName: 'McLaren' },
  { modelId: 'GT', modelName: 'GT', brandId: 'MCL', brandName: 'McLaren' },
  { modelId: 'SENNA', modelName: 'Senna', brandId: 'MCL', brandName: 'McLaren' },
];

export const preparedModels = MODEL_SEED.map((m) => ({
  modelId: m.modelId,
  modelName: m.modelName,
  brandId: m.brandId,
  brandName: m.brandName,
  active: true,
}));

export const CITY_SEED = [
  { cityName: 'Lahore', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Faisalabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Rawalpindi', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Gujranwala', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Multan', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Sargodha', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Sialkot', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Bahawalpur', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Gujrat', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Sheikhupura', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Dera Ghazi Khan', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Sahiwal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Jhang', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Khanewal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Okara', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Vehari', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Toba Tek Singh', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Pak Pattan Sharif', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Bhalwal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Bhakkar', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Mandi Bahauddin', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Nankana Sahib', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Narowal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Shahkot', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Wazirabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Kasur', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Muridke', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Pattoki', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Phalia', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Jauharabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Chiniot', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Chishtian', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Muzaffar Gargh', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Kamalia', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Kabirwala', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Pir Mahal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Raiwind', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Renala Khurd', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Sadiqabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Mian Channu', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Mian Wali', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Daska', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Hafizabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Haroonabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Hasilpur', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Kot Addu', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Jaranwala', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Pindi Gheb', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Talagang', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Lala Musa', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Gujar Khan', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Fateh Jang', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Dina', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Taxila', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Jhelum', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Kharian', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Karachi', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Hyderabad', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Sukkur', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Nawabshah', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Mirpur Khas', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Ghotki', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Larkana', provinceId: 'SD', provinceName: 'Sindh' },
  { cityName: 'Peshawar', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Abbottabad', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Haripur', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Mardan', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Swabi', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Swat', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Nowshera', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Kohat', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Bannu', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Charsadda', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Dera Ismail Khan', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Mansehra', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Hassan Abdal', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Kamra', provinceId: 'KP', provinceName: 'KPK' },
  { cityName: 'Khanpur', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Khushab', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Chakwal', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Attock', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Chichawatni', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Arifwala', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Burewala', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Abdul Hakeem', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Khanpur', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Layyah', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Lodhran', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Bahawalnagar', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Rahim Yar Khan', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Raiwind', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Mian Wali', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Hafizabad', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Chunian', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Pindi Gheb', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'D.G.Khan', provinceId: 'PB', provinceName: 'Punjab' },
  { cityName: 'Mirpur A.K.', provinceId: 'AJK', provinceName: 'Azad Jammu and Kashmir' },
  { cityName: 'Quetta', provinceId: 'BA', provinceName: 'Balochistan' },
  { cityName: 'Islamabad', provinceId: 'ICT', provinceName: 'Islamabad Capital Territory' },
];

export const generateCityId = (cityName, index) => {
  const clean = (cityName || '').trim();
  if (!clean) return `CITY-${index}`;
  const prefix = clean
    .split(/\s+/)
    .map((w) => w[0])
    .join('')
    .slice(0, 3)
    .toUpperCase();
  const suffix = String(index + 1).padStart(3, '0');
  return `${prefix}-${suffix}`;
};

export const preparedCities = CITY_SEED.map((c, i) => ({
  cityId: generateCityId(c.cityName, i),
  cityName: c.cityName,
  provinceId: c.provinceId,
  provinceName: c.provinceName,
  active: true,
}));

const run = async () => {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('Set MONGODB_URI in backend/.env');
    process.exit(1);
  }

  await mongoose.connect(uri);

  await Vehicle.deleteMany({});
  await Vehicle.insertMany(vehicles);

  await VehicleAttribute.deleteMany({});
  await VehicleAttribute.insertMany(ATTRIBUTE_SEED);

  await Province.deleteMany({});
  await Province.insertMany(preparedProvinces);

  await Make.deleteMany({});
  await Make.insertMany(preparedMakes);

  await VehicleModel.deleteMany({});
  await VehicleModel.insertMany(preparedModels);

  await City.deleteMany({});
  await City.insertMany(preparedCities);

  const adminEmail = process.env.ADMIN_USERNAME || 'waseemsamra@gmail.com';
  await User.deleteOne({ username: adminEmail });
  const admin = new User({ username: adminEmail, email: adminEmail, role: 'admin' });
  admin.setPassword(process.env.ADMIN_PASSWORD || 'admin123');
  await admin.save();

  console.log(`Seeded ${vehicles.length} vehicles, ${ATTRIBUTE_SEED.length} attributes, ${preparedProvinces.length} provinces, ${preparedMakes.length} makes, ${preparedModels.length} models, ${preparedCities.length} cities; admin user: ${adminEmail}`);
  await mongoose.disconnect();
};

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
